### ISSUE TITLE
lineage tree download in svg file doesn't work

### ISSUE THREAD

**Issue by Lenardzhan** [unipept/unipept#1168]
Hi,

I attempt to download the lineage tree in svg file, but there's nothing when I open the svg file in Adobe Illustrate or other svg editing software. Please see attached screenshot.

Thanks,

Lenard Zhan
![Screenshot_2020-08-14 Tryptic peptide analysis of ADAAAEPAKPESSKPESSK Unipept](https://user-images.githubusercontent.com/69700282/90299004-01646100-de5a-11ea-9865-8c33e488573b.png)
![AI svg](https://user-images.githubusercontent.com/69700282/90299109-78015e80-de5a-11ea-9de3-bbf096061bb0.png)

**Comment by ninewise** [comment]
Would it be possible to attach the broken SVG file? We can have a look at what's going wrong.

**Comment by Lenardzhan** [comment]
Please find the SVG file attached. When I download this SVG file from Unipept and open it with AI, it’s blank with nothing.

Thanks.

**Comment by Lenardzhan** [comment]
> 
> 
> Would it be possible to attach the broken SVG file? We can have a look at what's going wrong.

I tried to attach SVG file, but github don't support the SVG file type.  Can I send you by email?

**Comment by pdawyndt** [comment]
unipept@ugent.be

**Comment by Lenardzhan** [comment]
Hi,

Please find the broken SVG file attached.

Thanks,

Lenard

**Comment by pverscha** [comment]
Hi @Lenardzhan,

This was indeed an issue with the current version of Unipept. The treeview visualization was being converted wrongly to SVG, producing an invalid file. The unipept web application has been updated and the issue should be resolved now. Thanks for reporting it! (Please let me know, if you still encounter problems).

_A little sidenote: if you try to download an SVG for the treemap visualization (**not the treeview, but the treemap**, if you should also need this), it will be blank when you open it in most graphics software suites. This is due to the fact that the treeview is rendered as HTML instead of pure SVG and that we are required to use the SVG `foreignObject`-tag (see [this](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject)). This tag, however, is not supported by some graphics software suites and thus leads to an empty canvas when opening the SVG with one of these applications. I suggest to use the PNG-export in this case, which already produces images of a relatively high resolution._

**Comment by Lenardzhan** [comment]
> 
> 
> Hi @Lenardzhan,
> 
> This was indeed an issue with the current version of Unipept. The treeview visualization was being converted wrongly to SVG, producing an invalid file. The unipept web application has been updated and the issue should be resolved now. Thanks for reporting it! (Please let me know, if you still encounter problems).
> 
> _A little sidenote: if you try to download an SVG for the treemap visualization (**not the treeview, but the treemap**, if you should also need this), it will be blank when you open it in most graphics software suites. This is due to the fact that the treeview is rendered as HTML instead of pure SVG and that we are required to use the SVG `foreignObject`-tag (see [this](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject)). This tag, however, is not supported by some graphics software suites and thus leads to an empty canvas when opening the SVG with one of these applications. I suggest to use the PNG-export in this case, which already produces images of a relatively high resolution._

I find it works now. Thanks very much!
