### ISSUE TITLE
recompute LCA upon updating selected peptidomes

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#279]
The lowest common ancestor (LCA) should be recomputed each time peptidomes are added to or removed from the list of selected peptidomes. Now, it seems the LCA on gets computed once, and is never updated again.

I agree that for the time being, ony the peptidomes derived from RefSeq genomes are used to compute the LCA, and that user-uploaded peptidomes are not taken into account. Otherwise, the user would also have to specify the taxon_id for his uploaded peptidome.

_[Original issue](https://github.ugent.be/unipept/unipept/issues/279) by @pdawyndt on Wed May 07 2014 at 06:52._
_Closed by @bmesuere on Thu May 15 2014 at 18:57._

**Comment by bmesuere** [comment]
@pdawyndt Do you have a reproducible scenario?
This works both on scruffy and unipept:
- load Acinetobacter baumanii -> LCA = Acinetobacter baumanii
- add Acinetobacter calcoaceticus -> LCA = Acinetobacter calcoaceticus/baumannii complex
- add Acinetobacter oleivorans -> LCA = Acinetobacter
  You do have to wait until the "unique peptides" are loaded because the LCA calculation happens in the same query.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/279#issuecomment-9290) by @bmesuere on Wed May 07 2014 at 09:25._

**Comment by pdawyndt** [comment]
here's a scenario:
- start with a new session of the unique peptide filter application; initially the LCA is given as `undefined` and the correct LCA is shown at the time the green line is drawn (so far so good)
- clear all selected peptidomes; now I would already expect that the LCA turns back to `undefined`, but it remains to be given as `Acinetobacter baumanii`
- add peptidomes derived from all Klebsiella genomes; now the LCA remains `undefined` until the green line is drawn, after which the LCA is modified into `root`


_[Original comment](https://github.ugent.be/unipept/unipept/issues/279#issuecomment-9295) by @pdawyndt on Wed May 07 2014 at 11:37._
