### ISSUE TITLE
handle degenerated residues

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#344]
some uniprot records contain degenerated residues (X, Z, B, ...) that should be taken into account (requires inexact matching); should contact Lennart with @ninewise to discuss how this should be taken into account for the indexing

_[Original issue](https://github.ugent.be/unipept/unipept/issues/344) by @pdawyndt on Fri May 23 2014 at 11:22._
_Closed by @bmesuere on Mon Feb 01 2016 at 14:17._

**Comment by bmesuere** [comment]
`@tvwillem` and I already discussed this with Lennart. Of the first million sequences, only 29 of them contain Z, B or J. Since these sequences are unreliable by definition and their quantity is negligibly small, we concluded it's safe to ignore them. Especially since this would require a significant effort and result in a minimal potential gain.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/344#issuecomment-9885) by @bmesuere on Fri May 23 2014 at 11:52._

**Comment by pdawyndt** [comment]
Lennart indeed reminded me about this. I just added it to github, so that we recall it for next year. I guess this is something @ninewise can look into next year.


_[Original comment](https://github.ugent.be/unipept/unipept/issues/344#issuecomment-9888) by @pdawyndt on Fri May 23 2014 at 12:06._

**Comment by bmesuere** [comment]
not an issue


_[Original comment](https://github.ugent.be/unipept/unipept/issues/344#issuecomment-24503) by @bmesuere on Mon Feb 01 2016 at 14:17._
