### ISSUE TITLE
start update process automatically

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#480]
@ninewise the update process of Unipept can be triggered by following the [UniProt RSS feed](http://www.uniprot.org/downloads). On the same page, also see alternative FTP servers for downloads from Europe (servers in UK or Switzerland).

_[Original issue](https://github.ugent.be/unipept/unipept/issues/480) by @pdawyndt on Tue Apr 07 2015 at 12:56._

**Comment by bmesuere** [comment]
This might be worth reconsidering. These are the step I now take:
1. stop the mysql database on adler (because we need the memory)
2. start the make file
3. wait
4. copy the generated files to a separate dir on adler, to sherlock and to mycroft
5. start the mysql database on adler
6. drop `unipept` on adler and `unipept2` on sherlock and mycroft
7. recreate all tables on all servers
8. run `load.sh && index.sh` on all servers
9. run `loadProteomes.sh` on adler
10. delete the cache dir on adler
11. manually check the results on adler
12. bump the unipept version number
13. swap the databases on sherlock and mycroft
14. deploy a new release on sherlock and mycroft
15. run `loadProteomes.sh` on sherlock
16. delete the cache dir on sherlock


_[Original comment](https://github.ugent.be/unipept/unipept/issues/480#issuecomment-24506) by @bmesuere on Mon Feb 01 2016 at 14:44._
