### ISSUE TITLE
usabilty test: IE11

### ISSUE THREAD

**Issue by pdawyndt** [unipept/unipept#525]
I guided prof. Paul De Vos through making a clustering of the proteomes of _Bacillus cereus_, _B. thruringiensis_ and _B. cytotoxicus_ in Internet Explorer 11. Here are some things that have gone wrong when using this browser:
- [ ] after clustering, some names to the right of the similarity matrix disappear
- [ ] download a clustering as a PNG does not work (download as SVG does work)
- [ ] list of "analyzed proteomes" remains empty, although proteomes have been added to the clustering
- [ ] sorting the proteomes (e.g. by name) never finishes

A more elaborate testing with this browsers seems needed

_[Original issue](https://github.ugent.be/unipept/unipept/issues/525) by @pdawyndt on Thu Aug 06 2015 at 13:02._
_Closed by @bmesuere on Fri Aug 07 2015 at 14:39._

**Comment by bmesuere** [comment]
There are 2 separate issues:
- The PNG download
- The rest

The PNG download is broken because:
- IE doesn't support the download attribute in links so a new tab is opened instead of downloading the file.
- The image is stored as a data-URI. IE doesn't support showing an image by data-URI in a new tab.

The only "solution" is to remove the download PNG button in IE.

The other issues are because of a bug in the ES6-collections polyfill. It seems like `clear` is not properly clearing the map. The issues was reported here: https://github.com/WebReflection/es6-collections/issues/35


_[Original comment](https://github.ugent.be/unipept/unipept/issues/525#issuecomment-19326) by @bmesuere on Fri Aug 07 2015 at 13:54._

**Comment by bmesuere** [comment]
fixed in c4ff08e4cfa3b5cf2eb45fc443bd3f4614c19428 and 3.0.3


_[Original comment](https://github.ugent.be/unipept/unipept/issues/525#issuecomment-19329) by @bmesuere on Fri Aug 07 2015 at 14:39._
