### ISSUE TITLE
Unipept taxonomy infomation is inconsistent with NCBI

### ISSUE THREAD

**Issue by lhuangjs** [unipept/unipept#6]
Hello, When I retrieved taxonomy information by Unipept `taxonomy API`, my input `taxon id` is **373870**, I get
```
[{"taxon_id":373870,"taxon_name":"Meliniomyces bicolor","taxon_rank":"species"}]
```
However, When I retrieved taxonomy information by NCBI, my input `taxon id` also is **373870**, I get
![image](https://user-images.githubusercontent.com/15766876/53461782-ad569880-3a7c-11e9-9aa3-24f7a4a9cd37.png)

```
Unipept  - taxon_id: 373870,  taxon_name: Meliniomyces bicolor
NCBI     - taxon_id: 2482752, taxon_name: Hyaloscypha bicolor
```

I assumed that it is because the taxonomy annotation version is inconsistent, Right?
if so, will Unipept taxonomy information be consistent with NCBI taxonomy information? How often?

**Comment by bmesuere** [comment]
There can be multiple reasons for this:
- We use the taxon id associated with the UniProt records. If NCBI updates or merges some id's, I can't guarantee that UniProt instantly also updates all entries. If I'm not mistaken, it takes multiple months to run the entire UniProt pipeline, so it might take some time for a change in the taxonomy to propagate.
- We try to fix this a little bit when parsing UniProt by looking up the official name in case a synonym was used in UniProt.
- We try to update the Unipept sources data once every 6 months. We could do this more often, but since researchers rely on our data, some stability in results is also needed. We can't only update the taxonomy, we also must run the entire UniProt step.

I hope this answers your question!

**Comment by lhuangjs** [comment]
Thank you for your help.
