### ISSUE TITLE
update html2canvas to 0.5

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept#608]
- switch dep to yarn
- update to new promise interface

_[Original issue](https://github.ugent.be/unipept/unipept/issues/608) by @bmesuere on Wed Jul 05 2017 at 11:35._

**Comment by bmesuere** [comment]
The original maintainer of the package is back and working on version 1.0 with breaking changes. We should wait till then to update


_[Original comment](https://github.ugent.be/unipept/unipept/issues/608#issuecomment-69803) by @bmesuere on Thu Aug 17 2017 at 11:50._

**Comment by pverscha** [comment]
Version 1.0.0-rc.5 still causes issues (possibly because it is still not a 100% stable release), so I decided to replace html2canvas by html-to-image (https://www.npmjs.com/package/html-to-image), which seems to be working better (except for some errors that occur while trying to load webfonts).

Since we don't need the webfonts to be loaded into our image, I forked the library and disabled these. I plan on taking a closer look in the future and hopefully fix this issue for the original library.
