### ISSUE TITLE
peptinfo API return a different information than the Tryptic Peptide Analysis

### ISSUE THREAD

**Issue by lhuangjs** [unipept/unipept#7]
Hello, the function of the `peptinfo API`  is 
> This method returns functional information and the lowest common ancestor a given tryptic peptide. This is the same information as provided when performing a search with the Tryptic Peptide Analysis in the web interface.

However, I get different results from `Tryptic Peptide Analysis` and `peptinfo API`. my input peptide is `AAAAAAEMEKKPAPK`.

- `Tryptic Peptide Analysis` result

![image](https://user-images.githubusercontent.com/15766876/53555084-330d3d80-3b7c-11e9-9afe-ae4fbd33ee1d.png)

The LCA is `Akkermansia muciniphila` and on `species` rank.

- `peptinfo API` result

![image](https://user-images.githubusercontent.com/15766876/53554667-39e78080-3b7b-11e9-97e2-b038e8f81dac.png)

The LCA is null.

Then, I try to retrieve by `Metaproteomics Analysis` in two conditions.

- `Metaproteomics Analysis` without `Advanced missed cleavage handling`

![image](https://user-images.githubusercontent.com/15766876/53554791-87fc8400-3b7b-11e9-904f-4b18f9a16377.png)

The LCA is null.

- `Metaproteomics Analysis` with `Advanced missed cleavage handling`

![image](https://user-images.githubusercontent.com/15766876/53554885-be3a0380-3b7b-11e9-9458-d44e757eea3a.png)

The LCA is `Akkermansia muciniphila`

So I think the input peptides are split by default in `peptinfo API` and user cannot control the operation.

**Comment by bmesuere** [comment]
- The API supports no missed cleavage handling at the moment. Since our index only contains "real" tryptic peptides, the API call returns no results.
- The results of the tryptic peptide analysis (TPA) should correspond with the metaproteomics analysis (MPA), since it does "advanced missed cleavage handling" which means that we try to match the entire peptide in the protein sequence. This is quite heavy to calculate, which is why we don't enable it by default on the MPA and don't support it with the API
- The default behaviour of the MPA is to perform an in silico digest and report of the resulting fragments (without recombining them)

What you are reporting is in line with the expected behaviour. We do plan to take another look at the missed cleavage handling of the API and CLI. If we get the necessary funding, we would also like to develop a desktop tool which would combine the speed of the API with the interface of the web site which would also include the advanced options.

**Comment by lhuangjs** [comment]
Ok, thanks. However, should you post a warning about not support `missed cleavage` at the API document?

**Comment by bmesuere** [comment]
Fair point, we'll add such notice with the next release. Thanks for reporting!
